title: Projects & Notes
description: >-
  A workshop log of things I build, maybe that could help anyone facing the
  same challenges 😉
baseurl: ""
url: "https://gharlyk.github.io"

theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme nav
minima:
  nav_pages:
    - about.md
    - projects.md
